export const all_property = [
  { key: "AHEW", label: "AHEW" },
  { key: "Amine_value", label: "Amine value" },
  { key: "Colour", label: "Colour" },
  { key: "Feature", label: "Feature" },
  { key: "Gel_time", label: "Gel time" },
  { key: "HEW", label: "HEW" },
  { key: "Melt_viscosity", label: "Melt viscosity" },
  { key: "Mix_viscosity", label: "Mix viscosity" },
  { key: "Mixing_ratio", label: "Mixing ratio" },
  { key: "PHR", label: "PHR" },
  { key: "Pot_life", label: "Pot life" },
  { key: "Solid_content", label: "Solid content" },
  { key: "Specific_gravity", label: "Specific gravity" },
  { key: "TFST", label: "Thin film set time" },
  { key: "Viscosity", label: "Viscosity" },
  { key: "Density", label: "Density" },
  // New
  { key: "Resin_used", label: "Resin used" },

  // Changed
  { key: "Appearance", label: "Appearance" },
  { key: "EEW", label: "Epoxy Equivalent Weight" },
  { key: "Hydrolysable_chlorine", label: "Hydrolysable Chlorine" },
  { key: "Nonvolatiles", label: "Non-volatile content" },
  { key: "Softening_point", label: "Softening point" },
  // Necessary
  { key: "Refractive_index", label: "Refractive index" },
  { key: "Epoxide_value", label: "Epoxide value" },
  // Modified
  { key: "Water_content", label: "Water content" },
  { key: "ECH_content", label: "ECH content" },
  { key: "Flash_point", label: "Flash point" },
  { key: "Fuctionality", label: "Fuctionality" },
  { key: "Tensile_strength", label: "Tensile strength" },
  { key: "Amine_index", label: "Amine index" },
  { key: "Relative_density", label: "Relative density" },
  { key: "Compressive_st", label: "Compressive strength" },
  { key: "Flexural_st", label: "Flexural strength" },
  { key: "Glass_tr_temp", label: "Glass transition temperature" },
  { key: "Bulk_density", label: "Bulk density" },
  { key: "Odour", label: "Odour" },
  { key: "Softening_Point", label: "Softening Point" },
  { key: "Insoluble_content", label: "Insoluble content" },
  { key: "Insolubles", label: "Insolubles" },
  { key: "Volume_MPS", label: "Volume Mean Particle Size" },
  { key: "Hydroxyl_value", label: "Hydroxyl value" },
  //   { key: "Glass_t_temp", label: "Glass transition Temperature" },
];
